-- Create customers main table
CREATE TABLE customers (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status BOOLEAN DEFAULT TRUE NOT NULL,
    customer_code VARCHAR(50) UNIQUE NOT NULL,
    customer_name VARCHAR(255),
    customer_sales_area VARCHAR(50),
    customer_sales_owner VARCHAR(100),
    customer_service_owner VARCHAR(100),
    customer_price_list VARCHAR(50),
    customer_discount DECIMAL(5,2),
    customer_payment_terms INTEGER,
    customer_tax_prefix VARCHAR(10),
    customer_tax_number VARCHAR(20),
    customer_address_street VARCHAR(255),
    customer_address_country VARCHAR(100),
    customer_address_zip VARCHAR(20),
    customer_address_city VARCHAR(100),
    customer_phone_number VARCHAR(30),
    customer_fax_number VARCHAR(30),
    customer_email VARCHAR(255),
    customer_addresses JSONB DEFAULT '[]',
    customer_contacts JSONB DEFAULT '[]',
    customer_credits JSONB DEFAULT '[]'
);